apiVersion: v1
kind: Service
metadata:
  name: reddit-clone-service
  labels:
    app: reddit-clone
spec:
  type: NodePort
  selector:
    app: reddit-clone
  ports:
    - nodePort: 31479
      port: 8080
      targetPort: 3000